---
# Handlers for Splunk Enterprise role

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart splunk
  systemd:
    name: splunk
    state: restarted
  listen: "restart splunk"

- name: reload splunk
  command: "{{ splunk_home }}/bin/splunk reload deploy-server"
  become_user: "{{ splunk_user }}"
  listen: "reload deployment server"
