---
# Dedicated playbook for GitHub configuration updates
- name: Update Splunk Configuration from GitHub
  hosts: splunk_deployment_servers
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Validate GitHub configuration
      assert:
        that:
          - github_token is defined
          - github_repo_url is defined
        fail_msg: "GitHub token and repository URL are required"
        
    - name: Include GitHub integration role
      include_role:
        name: github_integration
        
    - name: Reload deployment server
      command: "{{ splunk_home }}/bin/splunk reload deploy-server"
      become_user: "{{ splunk_user }}"
      
    - name: Verify configuration update
      uri:
        url: "https://localhost:8089/services/deployment/server"
        user: admin
        password: "{{ splunk_admin_password }}"
        method: GET
        validate_certs: no
        status_code: 200
      register: deployment_status
      
    - name: Display update status
      debug:
        msg: "Configuration update from GitHub completed successfully"
      when: deployment_status.status == 200
