version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
      - apt-get install -y openjdk-17-jdk unzip wget imagemagick librsvg2-bin

  pre_build:
    commands:
      - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      - unzip -q commandlinetools-linux-9477386_latest.zip
      - mkdir -p android-sdk/cmdline-tools/latest
      - mv cmdline-tools/* android-sdk/cmdline-tools/latest/
      - export ANDROID_HOME=$PWD/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --licenses || true
      - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"

  build:
    commands:
      - export ANDROID_HOME=$PWD/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      - echo Using core-only configuration...
      - cp app-core.json app.json
      - cp package-core.json package.json
      - rm -rf node_modules package-lock.json
      - npm config set legacy-peer-deps true
      - npm install --production --no-optional --ignore-scripts
      - rsvg-convert -w 1024 -h 1024 assets/icon.svg -o assets/icon.png
      - rsvg-convert -w 1024 -h 1024 assets/adaptive-icon.svg -o assets/adaptive-icon.png
      - rsvg-convert -w 2048 -h 2048 assets/splash.svg -o assets/splash.png
      - rsvg-convert -w 32 -h 32 assets/favicon.svg -o assets/favicon.png
      - rm -rf android ios
      - npx --package=@expo/cli@latest expo prebuild --platform android --no-install
      - cd android/app
      - echo 'android.compileSdkVersion=33' >> gradle.properties
      - echo 'android.targetSdkVersion=33' >> gradle.properties  
      - echo 'android.buildToolsVersion=33.0.0' >> gradle.properties
      - cd ../..
      - cd android
      - chmod +x ./gradlew
      - ./gradlew clean bundleRelease --no-daemon --stacktrace --info
      - cd ..

  post_build:
    commands:
      - find . -name "*.aab" -exec cp {} ./rock-crush.aab \;
      - ls -la *.aab

artifacts:
  files:
    - '*.aab'
