version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing system dependencies...
      - apt-get update
      - apt-get install -y openjdk-17-jdk unzip wget
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      
  pre_build:
    commands:
      - echo Installing Expo CLI...
      - npm install -g @expo/cli
      - echo Setting up Android SDK...
      - wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      - unzip -q commandlinetools-linux-9477386_latest.zip
      - mkdir -p android-sdk/cmdline-tools/latest
      - mv cmdline-tools/* android-sdk/cmdline-tools/latest/
      - export ANDROID_HOME=$PWD/android-sdk
      - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
      - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - yes | sdkmanager --licenses || true
      - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      
  build:
    commands:
      - echo Starting build process...
      - echo Installing project dependencies...
      - npm install
      - echo Authenticating with Expo...
      - echo "machine expo.dev login expo password $EXPO_TOKEN" > ~/.netrc
      - echo Building production AAB for Play Store...
      - npx eas build --platform android --profile production --non-interactive --wait
      - echo Build completed successfully
      
  post_build:
    commands:
      - echo Locating AAB file...
      - find . -name "*.aab" -type f
      - echo Uploading AAB to S3...
      - find . -name "*.aab" -type f -exec aws s3 cp {} s3://rock-crush-builds/rock-crush-$(date +%Y%m%d-%H%M%S).aab \;
      - echo Upload completed

artifacts:
  files:
    - '**/*.aab'
  name: rock-crush-playstore-build