[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ansible>=11.8.0",
    "ansible-core>=2.18.7",
    "jinja2>=3.1.6",
    "netaddr>=1.3.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
