---
# Common default variables
system_timezone: "UTC"
deployment_log_file: "/var/log/ansible-splunk-deployment.log"

# Firewall ports for Splunk
splunk_ports:
  - port: 8000
    protocol: tcp
    description: "Splunk Web Interface"
  - port: 8089
    protocol: tcp
    description: "Splunk Management Port"
