---
# Common tasks for all servers

- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == "apt"
  
- name: Update package cache (yum)
  yum:
    update_cache: yes
  when: ansible_pkg_mgr == "yum"

- name: Install required packages (apt)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - tar
    - unzip
    - python3
    - python3-pip
    - git
    - rsync
    - cron
  when: ansible_pkg_mgr == "apt"
  
- name: Install required packages (yum)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - tar
    - unzip
    - python3
    - python3-pip
    - git
    - rsync
    - cronie
  when: ansible_pkg_mgr == "yum"

- name: Configure firewall for Splunk ports
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ splunk_ports }}"
  ignore_errors: yes

- name: Set timezone
  timezone:
    name: "{{ system_timezone | default('UTC') }}"

- name: Configure system limits for Splunk
  pam_limits:
    domain: "{{ splunk_user }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - { type: 'soft', item: 'nofile', value: '65536' }
    - { type: 'hard', item: 'nofile', value: '65536' }
    - { type: 'soft', item: 'nproc', value: '16384' }
    - { type: 'hard', item: 'nproc', value: '16384' }

- name: Configure kernel parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: 'vm.max_map_count', value: '262144' }
    - { name: 'fs.file-max', value: '2097152' }

- name: Create log directory
  file:
    path: /var/log/ansible
    state: directory
    mode: '0755'

- name: Setup log rotation for deployment logs
  copy:
    content: |
      {{ deployment_log_file }} {
          daily
          rotate 30
          compress
          delaycompress
          notifempty
          create 644 root root
      }
    dest: /etc/logrotate.d/ansible-splunk-deployment
    mode: '0644'
 