---
# Specific playbook for deploying Splunk Deployment Server
- name: Deploy Splunk Enterprise Deployment Server
  hosts: splunk_deployment_servers
  become: yes
  gather_facts: yes
  
  vars:
    deployment_type: "deployment_server"
    
  pre_tasks:
    - name: Validate deployment server requirements
      assert:
        that:
          - splunk_admin_password is defined
          - splunk_deployment_server_pass4symmkey is defined
        fail_msg: "Required deployment server variables are missing"
        
  tasks:
    - name: Include common role
      include_role:
        name: common
        
    - name: Include Splunk Enterprise role
      include_role:
        name: splunk_enterprise
        
    - name: Include backup restoration role
      include_role:
        name: backup_restoration
      when: restore_from_backup | default(false)
      
    - name: Include GitHub integration role
      include_role:
        name: github_integration
      when: github_token is defined
      
  post_tasks:
    - name: Verify deployment server functionality
      uri:
        url: "https://{{ ansible_default_ipv4.address }}:8089/services/deployment/server"
        user: admin
        password: "{{ splunk_admin_password }}"
        method: GET
        validate_certs: no
        status_code: 200
      register: deployment_server_status
      
    - name: Display deployment server status
      debug:
        msg: "Deployment server is {{ 'active' if deployment_server_status.status == 200 else 'inactive' }}"
